### ISSUE TITLE
Fabric version doesn't work in 1.15.2

### ISSUE THREAD

**Issue by Br31zh** [Naxanria/itemgot#5]
The game crash when I join a world, here is the crash report :

```
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2020-03-08 11:14:28 CET
Description: Unexpected error

java.lang.NoClassDefFoundError: com/mojang/blaze3d/platform/GlStateManager
    at Not Enough Crashes deobfuscated stack trace.(1.15.2+build.14)
    at com.naxanria.itemgot.GUIHud.onRenderHud(GUIHud.java:80)
    at net.minecraft.client.gui.hud.InGameHud.handler$zzg000$onDraw(InGameHud:1295)
    at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:431)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:736)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:989)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:619)
    at net.minecraft.client.main.Main.main(Main:204)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.ClassNotFoundException: com.mojang.blaze3d.platform.GlStateManager
    at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
    at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    ... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  All players: 1 total; [class_746['Br31zh'/91, l='MpServer', x=8.50, y=65.00, z=8.50]]
  Chunk stats: Client Chunk Cache: 729, 0
  Level dimension: minecraft:overworld
  Level name: MpServer
  Level seed: -1992643309670086991
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: {}
  Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 1 game time, 1 day time
  Known server brands: 
  Level was modded: false
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Server brand: fabric
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.15.2
  Minecraft Version ID: 1.15.2
  Operating System: Linux (amd64) version 5.5.8-arch1-1
  Java Version: 11.0.6, Oracle Corporation
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 419917360 bytes (400 MB) / 1040187392 bytes (992 MB) up to 2147483648 bytes (2048 MB)
  CPUs: 12
  JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Item Got (itemgot), Fabric Loader (fabricloader)
  Fabric Mods: appleskin: AppleSkin 1.0.8
               autoconfig1u: Auto Config v1 Updated 1.2.4
               cloth: Cloth Events 1.2.0
               cloth-config2: Cloth Config v2 2.10
               durabilityviewer: Giselbaers Durability Viewer 1.15.2-fabric0.4.23-1.7
               fabric: Fabric API 0.4.32+build.292-1.15
               fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
               fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
               fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
               fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
               fabric-dimensions-v1: fabric-dimensions-v1 0.2.4+203491ea0c
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.7+a1bd31180c
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d0c
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
               fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
               fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
               fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
               fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
               fabricloader: Fabric Loader 0.7.8+build.184
               gbfabrictools: GBfabrictools 1.2.0
               itemgot: Item Got 1.0.4
               lightoverlay: Light Overlay 4.2
               loadcatcher: Entrypoint Catcher 1.1.0
               me_shedaniel_cloth_basic-math: basic-math 0.3.0
               minecraft: Minecraft 1.15.2
               mm: Manningham Mills 2.0
               modmenu: Mod Menu 1.10.1+build.30
               notenoughcrashes: Not Enough Crashes 1.2.2+1.15.1
               notenoughcrashes-api: Not Enough Crashes API 1.0.0
               optifabric: Optifabric 1.0.0-beta4
               org_jetbrains_annotations: annotations 18.0.0
               org_slf4j_slf4j-api: slf4j-api 1.7.30
               org_slf4j_slf4j-simple: slf4j-simple 1.7.30
               org_zeroturnaround_zt-zip: zt-zip 1.14
               roughlyenoughitems: Roughly Enough Items 3.6.1
               voxelmap: VoxelMap 1.9.14
               waila: Hwyla 1.9.20
               worldtime: WorldTime 1.15-fabric0.4.23-1.1
  Launched Version: fabric-loader-0.7.8+build.184-1.15.2
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: Radeon RX 590 Series (POLARIS10, DRM 3.36.0, 5.5.8-arch1-1, LLVM 9.0.1) GL version 4.5 (Compatibility Profile) Mesa 19.3.4, X.Org
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Resource Packs: vanilla, file/1.15.2-r1.zip, file/Faithful+3D+1.15.2+v1.zip
  Current Language: English (US)
  CPU: 12x AMD Ryzen 5 2600X Six-Core Processor
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0
```

I have Fabric API, so it's not the same error than issue #1 . I've some mods, so I made a second test with only Item Got and Fabric API :

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 08/03/2020 11:45
Description: Unexpected error

java.lang.NoClassDefFoundError: com/mojang/blaze3d/platform/GlStateManager
	at com.naxanria.itemgot.GUIHud.onRenderHud(GUIHud.java:80)
	at net.minecraft.class_329.handler$zzg000$onDraw(class_329.java:1295)
	at net.minecraft.class_329.method_1753(class_329.java:365)
	at net.minecraft.class_757.method_3192(class_757.java:585)
	at net.minecraft.class_310.method_1523(class_310.java:989)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.ClassNotFoundException: com.mojang.blaze3d.platform.GlStateManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.naxanria.itemgot.GUIHud.onRenderHud(GUIHud.java:80)
	at net.minecraft.class_329.handler$zzg000$onDraw(class_329.java:1295)
	at net.minecraft.class_329.method_1753(class_329.java:365)

-- Affected level --
Details:
	All players: 1 total; [class_746['Br31zh'/42, l='MpServer', x=12.62, y=59.03, z=5.82]]
	Chunk stats: Client Chunk Cache: 1369, 441
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -1380427240727859824
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (8,55,8), Chunk: (at 8,3,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 118719 game time, 118719 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:450)
	at net.minecraft.class_310.method_1587(class_310.java:1921)
	at net.minecraft.class_310.method_1514(class_310.java:639)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 5.5.8-arch1-1
	Java Version: 11.0.6, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1023196760 bytes (975 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.4.32+build.292-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.2.4+203491ea0c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.7+a1bd31180c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d0c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabricloader: Fabric Loader 0.7.8+build.184
		itemgot: Item Got 1.0.4
		minecraft: Minecraft 1.15.2
	Launched Version: fabric-loader-0.7.8+build.184-1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 590 Series (POLARIS10, DRM 3.36.0, 5.5.8-arch1-1, LLVM 9.0.1) GL version 4.5 (Compatibility Profile) Mesa 19.3.4, X.Org
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/1.15.2-r1.zip, file/Faithful+3D+1.15.2+v1.zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 2600X Six-Core Processor
```

**Comment by Naxanria** [comment]
It indeed does not work on fabric. It is a forge mod for 1.15.2

**Comment by Br31zh** [comment]
I thought the two versions cohabited and were maintained simultaneously. Thanks for your answer.
